alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: sample-golang
    match:
      path:
        prefix: /
name: hammerhead-app
region: blr
services:
- environment_slug: go
  github:
    branch: go-v1.22
    deploy_on_push: true
    repo: thearyanahmed/sample-golang
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: sample-golang
  run_command: bin/sample-golang
  source_dir: /
  build_command: go version && go mod tidy && go mod vendor && go build -o bin/hms ./main.go
